import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const usePostgres =
  process.env.VERCEL === "1" ||
  (process.env.DATABASE_URL ?? "").startsWith("postgres");

const dialect = usePostgres ? "pg" : "sqlite";

writeFileSync(
  join(root, "src/db/index.ts"),
  `// Generated by scripts/prepare-db.mjs — do not edit manually
export * from "./runtime-${dialect}";
`,
);

writeFileSync(
  join(root, "src/db/schema.ts"),
  `// Generated by scripts/prepare-db.mjs — do not edit manually
export * from "./schema-${dialect}";
`,
);

console.log(`DB dialect: ${dialect}`);
