import type { ProviderDefinition } from "./types";

export const PROVIDER_DEFINITIONS: ProviderDefinition[] = [
  // Chinese-first text
  {
    id: "deepseek",
    label: "DeepSeek",
    kind: "text",
    origin: "cn",
    free: true,
    envKey: "DEEPSEEK_API_KEY",
    signupUrl: "https://platform.deepseek.com/",
    baseUrl: "https://api.deepseek.com/v1",
    model: "deepseek-chat",
    description: "Strong Chinese reasoning model with free credits.",
  },
  {
    id: "qwen",
    label: "Qwen (DashScope)",
    kind: "text",
    origin: "cn",
    free: true,
    envKey: "DASHSCOPE_API_KEY",
    signupUrl: "https://dashscope.console.aliyun.com/",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    model: "qwen-plus",
    description: "Alibaba Qwen text generation.",
  },
  {
    id: "glm",
    label: "GLM (Zhipu / z.ai)",
    kind: "text",
    origin: "cn",
    free: true,
    envKey: "ZHIPU_API_KEY",
    signupUrl: "https://open.bigmodel.cn/",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    model: "glm-4-flash",
    description: "Zhipu GLM chat models.",
  },
  {
    id: "kimi",
    label: "Kimi (Moonshot)",
    kind: "text",
    origin: "cn",
    free: true,
    envKey: "MOONSHOT_API_KEY",
    signupUrl: "https://platform.moonshot.cn/",
    baseUrl: "https://api.moonshot.cn/v1",
    model: "moonshot-v1-8k",
    description: "Moonshot long-context text.",
  },
  {
    id: "minimax-text",
    label: "MiniMax Text",
    kind: "text",
    origin: "cn",
    free: true,
    envKey: "MINIMAX_API_KEY",
    signupUrl: "https://www.minimaxi.com/",
    baseUrl: "https://api.minimax.chat/v1",
    model: "abab6.5s-chat",
    description: "MiniMax conversational model.",
  },
  {
    id: "stepfun",
    label: "StepFun",
    kind: "text",
    origin: "cn",
    free: true,
    envKey: "STEPFUN_API_KEY",
    signupUrl: "https://platform.stepfun.com/",
    baseUrl: "https://api.stepfun.com/v1",
    model: "step-1-8k",
    description: "StepFun text generation.",
  },
  {
    id: "ernie",
    label: "ERNIE (Baidu)",
    kind: "text",
    origin: "cn",
    free: true,
    envKey: "ERNIE_API_KEY",
    signupUrl: "https://cloud.baidu.com/product/wenxinworkshop",
    description: "Baidu ERNIE text (mock media until key wired).",
  },
  {
    id: "hunyuan-text",
    label: "Hunyuan Text",
    kind: "text",
    origin: "cn",
    free: true,
    envKey: "HUNYUAN_API_KEY",
    signupUrl: "https://cloud.tencent.com/product/hunyuan",
    description: "Tencent Hunyuan text.",
  },
  // Chinese image/video
  {
    id: "qwen-image",
    label: "Qwen Image",
    kind: "image",
    origin: "cn",
    free: true,
    envKey: "DASHSCOPE_API_KEY",
    signupUrl: "https://dashscope.console.aliyun.com/",
    description: "Wanxiang / Qwen image generation.",
  },
  {
    id: "cogview",
    label: "CogView (GLM)",
    kind: "image",
    origin: "cn",
    free: true,
    envKey: "ZHIPU_API_KEY",
    signupUrl: "https://open.bigmodel.cn/",
    description: "Zhipu image generation.",
  },
  {
    id: "seedream",
    label: "Seedream (ByteDance)",
    kind: "image",
    origin: "cn",
    free: true,
    envKey: "VOLCENGINE_API_KEY",
    signupUrl: "https://www.volcengine.com/",
    description: "Volcengine Seedream images.",
  },
  {
    id: "hunyuan-image",
    label: "Hunyuan Image",
    kind: "image",
    origin: "cn",
    free: true,
    envKey: "HUNYUAN_API_KEY",
    signupUrl: "https://cloud.tencent.com/product/hunyuan",
    description: "Tencent Hunyuan images.",
  },
  {
    id: "hidream",
    label: "HiDream",
    kind: "image",
    origin: "cn",
    free: true,
    envKey: "HIDREAM_API_KEY",
    signupUrl: "https://hidream.ai/",
    description: "HiDream image generation.",
  },
  {
    id: "kling",
    label: "Kling (Kuaishou)",
    kind: "video",
    origin: "cn",
    free: true,
    envKey: "KLING_API_KEY",
    signupUrl: "https://klingai.com/",
    description: "Kling video generation.",
  },
  {
    id: "wan",
    label: "Wan / Tongyi Wanxiang",
    kind: "video",
    origin: "cn",
    free: true,
    envKey: "DASHSCOPE_API_KEY",
    signupUrl: "https://dashscope.console.aliyun.com/",
    description: "Alibaba Wan video.",
  },
  {
    id: "hailuo",
    label: "Hailuo (MiniMax Video)",
    kind: "video",
    origin: "cn",
    free: true,
    envKey: "MINIMAX_API_KEY",
    signupUrl: "https://www.minimaxi.com/",
    description: "MiniMax Hailuo video.",
  },
  {
    id: "cogvideo",
    label: "CogVideo (GLM)",
    kind: "video",
    origin: "cn",
    free: true,
    envKey: "ZHIPU_API_KEY",
    signupUrl: "https://open.bigmodel.cn/",
    description: "Zhipu CogVideo.",
  },
  {
    id: "vidu",
    label: "Vidu",
    kind: "video",
    origin: "cn",
    free: true,
    envKey: "VIDU_API_KEY",
    signupUrl: "https://www.vidu.studio/",
    description: "Shengshu Vidu video.",
  },
  {
    id: "seedance",
    label: "Seedance (ByteDance)",
    kind: "video",
    origin: "cn",
    free: true,
    envKey: "VOLCENGINE_API_KEY",
    signupUrl: "https://www.volcengine.com/",
    description: "Volcengine Seedance video.",
  },
  {
    id: "pixverse",
    label: "Pixverse",
    kind: "video",
    origin: "cn",
    free: true,
    envKey: "PIXVERSE_API_KEY",
    signupUrl: "https://pixverse.ai/",
    description: "Pixverse video generation.",
  },
  {
    id: "minimax-tts",
    label: "MiniMax TTS",
    kind: "audio",
    origin: "cn",
    free: true,
    envKey: "MINIMAX_API_KEY",
    signupUrl: "https://www.minimaxi.com/",
    description: "MiniMax text-to-speech.",
  },
  // Global
  {
    id: "gemini",
    label: "Google Gemini",
    kind: "text",
    origin: "global",
    free: true,
    envKey: "GOOGLE_GENERATIVE_AI_API_KEY",
    signupUrl: "https://aistudio.google.com/apikey",
    description: "Google Gemini text.",
  },
  {
    id: "groq",
    label: "Groq",
    kind: "text",
    origin: "global",
    free: true,
    envKey: "GROQ_API_KEY",
    signupUrl: "https://console.groq.com/",
    baseUrl: "https://api.groq.com/openai/v1",
    model: "llama-3.3-70b-versatile",
    description: "Fast free inference on Groq.",
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    kind: "text",
    origin: "global",
    free: true,
    envKey: "OPENROUTER_API_KEY",
    signupUrl: "https://openrouter.ai/",
    baseUrl: "https://openrouter.ai/api/v1",
    model: "meta-llama/llama-3.1-8b-instruct:free",
    description: "Access many free models via OpenRouter.",
  },
  {
    id: "huggingface",
    label: "Hugging Face",
    kind: "image",
    origin: "global",
    free: true,
    envKey: "HF_API_KEY",
    signupUrl: "https://huggingface.co/settings/tokens",
    description: "HF Inference API for images.",
  },
  {
    id: "together",
    label: "Together AI",
    kind: "text",
    origin: "global",
    free: true,
    envKey: "TOGETHER_API_KEY",
    signupUrl: "https://api.together.xyz/",
    baseUrl: "https://api.together.xyz/v1",
    model: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    description: "Together hosted models.",
  },
  {
    id: "fireworks",
    label: "Fireworks",
    kind: "text",
    origin: "global",
    free: true,
    envKey: "FIREWORKS_API_KEY",
    signupUrl: "https://fireworks.ai/",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    model: "accounts/fireworks/models/llama-v3p1-8b-instruct",
    description: "Fireworks fast inference.",
  },
  {
    id: "replicate",
    label: "Replicate",
    kind: "video",
    origin: "global",
    free: true,
    envKey: "REPLICATE_API_TOKEN",
    signupUrl: "https://replicate.com/",
    description: "Replicate image/video models.",
  },
  {
    id: "fal",
    label: "Fal.ai",
    kind: "video",
    origin: "global",
    free: true,
    envKey: "FAL_KEY",
    signupUrl: "https://fal.ai/",
    description: "Fal fast media generation.",
  },
  {
    id: "stability",
    label: "Stability AI",
    kind: "image",
    origin: "global",
    free: true,
    envKey: "STABILITY_API_KEY",
    signupUrl: "https://platform.stability.ai/",
    description: "Stable Diffusion images.",
  },
  {
    id: "luma",
    label: "Luma",
    kind: "video",
    origin: "global",
    free: true,
    envKey: "LUMA_API_KEY",
    signupUrl: "https://lumalabs.ai/",
    description: "Luma Dream Machine video.",
  },
  {
    id: "runway",
    label: "Runway",
    kind: "video",
    origin: "global",
    free: true,
    envKey: "RUNWAY_API_KEY",
    signupUrl: "https://runwayml.com/",
    description: "Runway Gen video.",
  },
  {
    id: "pika",
    label: "Pika",
    kind: "video",
    origin: "global",
    free: true,
    envKey: "PIKA_API_KEY",
    signupUrl: "https://pika.art/",
    description: "Pika video generation.",
  },
  {
    id: "elevenlabs",
    label: "ElevenLabs",
    kind: "audio",
    origin: "global",
    free: true,
    envKey: "ELEVENLABS_API_KEY",
    signupUrl: "https://elevenlabs.io/",
    description: "Premium voice synthesis (limited free tier).",
  },
];
